### ISSUE TITLE
Ruby 3.1 image

### ISSUE THREAD

**Issue by rainerborene** [bitnami/bitnami-docker-ruby#89]
See here https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

**Comment by carrodher** [comment]
Thanks for letting us know, as it is a new "major branch", it will require some manual changes on our side, that's the reason why it was not released automatically. The team will work on it during the next days/weeks.

**Comment by rainerborene** [comment]
Thanks!
